###############################################################################
#                                                                             #
#                         Quickfire Powershell Module                         #
#                               AI/GPT Functions                              #
#                                    v1.6.4                                   #
#                                                                             #
###############################################################################

# Chris Byrne - christopher.byrne@derivco.com.au

Function Invoke-QFAI {

    <#
    .SYNOPSIS
        Processes Win Verification and Game Play Analysis tickets via OpenAI.

    .DESCRIPTION
        This cmdlet will take the provided support incident information, and process it via OpenAI.
        The AI should detect Win Verification and Game Play Analysis tickets, and provide a JSON format object containing parameters for New-QFTicket.
        This is currently in development and further functions are planned to be added.

    .PARAMETER AutoMode
        When this parameter is set, the function call arguments generated by the AI will be passed to New-QFTicket automatically.
        This will perform a transaction audit, playchecks and game statistics reports based on the parameters received from the AI.
        By default, the output from AI is simply output to pipeline.

    .PARAMETER GPTURI
        The OpenAI Chat Completion endpoint URI. By default, this cmdlet will use the MIGS-OpenAI Azure endpoint.

    .PARAMETER REQNumber
        The REQNumber of the Remedy/Helix incident to process.
        If specified, this parameter will be included in the function parameters output to pipeline.
        This is a required parameter for New-QFTicket. If you specify the AutoMode parameter, this parameter is mandatory.

    .PARAMETER Query
        The text to be processed by OpenAI.
        Since this text can span multiple lines, You may need to enclose this text in a 'here-string' and assign to an object to pass to this cmdlet.
        e.g.:
        $Query = @'
        This is a here-string
        it will escape all the new lines and symbols in this string.
        '@

    .INPUTS
        This cmdlet accepts Query and REQNumber parameters via pipeline.

    .OUTPUTS   
        This cmdlet will output data to pipeline, this will vary depending on parameters passed to the function and any function calls generated by the AI.
    #>

    # Set up parameters that can be passed to the function
    [CmdletBinding(DefaultParameterSetName = 'Default')]
    param(

        [Parameter(ValueFromPipelineByPropertyName=$true,ParameterSetName='AutoMode')]
        [switch]$AutoMode,

        [Parameter(ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$GPTURI = 'https://migs-openai.openai.azure.com/openai/deployments/migs-gpt4-test/chat/completions?api-version=2023-07-01-preview',

        [Parameter(ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true,Position=2,ParameterSetName='AutoMode',Mandatory=$true)]
        [Parameter(ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true,Position=2,ParameterSetName='Default')]
        [ValidateNotNullOrEmpty()]
        [string]$REQNumber,

        [Parameter(ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true,Position=1)]
        [ValidateNotNullOrEmpty()]
        [string]$Query
    )

    $LibPath = ($PSScriptRoot -replace "\\src$","\lib\").trim()
    Invoke-Expression $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String(
        "W2J5dGVbXV0kSGFzaCA9IChHZXQtRmlsZWhhc2ggKCRMaWJQYXRoICsgIi5tZXRhZGF0YSIpIHwgU2VsZWN0LU9iamVjdCAtRX" +
        "hwYW5kUHJvcGVydHkgSGFzaClbMC4uMzFdDQokR1BUQVBJS2V5ID0gR2V0LUNvbnRlbnQgKCRMaWJQYXRoICsgIi5kZWZzIikg" +
        "LUVuY29kaW5nIFVURjggfCBDb252ZXJ0VG8tU2VjdXJlU3RyaW5nIC1LZXkgJEhhc2g=")
        )
    )

    # How to change the saved API Key...
    #$Key = $GPTAPIKey|ConvertTo-SecureString -AsPlainText -Force
    #[byte[]]$Hash = (Get-Filehash .\lib\.metadata|Select -ExpandProperty Hash)[0..31]
    #$Key|Convertfrom-SecureString -key $Hash |Out-File .\lib\.defs -Encoding utf8


    # System message/instructions content
    # @' is used to escape symbols in text strings. This way you can include line feeds, carriages returns, apostrophes and commas etc in the message. 
    $SystemMessage = @'
    You are an AI assistant acting providing support for an online casino.
    Your task is to analyze the user request submitted by our customers to determine the category of the request.
    You will then call the appropriate function to handle the request, if applicable.
    If no function calls are applicable, you should still provide at minimum the category and an empty array for the functions in JSON format.
    Only the required parameters for each function must be provided. The rest of them should be provided if you can successfully extract them from the user request.
    If you can't provide a value for a parameter, do not specify that parameter.
    
    CATEGORY_OPTIONS
    [1] Transaction Audits, Play Checks, Visual Round Results, Gameplay Statistics and Big Win Verification reports, or a player disputing their payout or claiming missing winnings. Set 'category' to 'winLegitimacy' and call the New-QFTicket function.
    The AuditStartDate and AuditEndDate parameters should be set, based on any timestamps or date of occurence provided in the user request.
    [2] Stuck or incomplete game rounds, or false games. Set 'category' to 'stuckRound'.
    [3] Game launch issues, such as an error message while trying to launch a game, or games are otherwise inoperable. Set 'category' to 'gameLaunch'.
    [4] Progressive jackpot issues. Set 'category' to 'progressiveJackpots'.
    [5] Game Add On issues, also known as GAO. A new game has not completed installation and configuration prior to the deadline for launch. Set 'category' to 'gameAddOn'.
    [6] Issues with Free Game Offers. This can include errors while making the API request to create and assign the Free Game Offers to a player, or the players having difficulty accepting and playing the offers. Set 'category' to 'freeGameOffers'.
    [7] Bet settings changes. This includes changes to maximum, minimum or default wagers, or adjustments to bonus buy/purchase bet limits. Set 'category' to 'betSettings'.
    [8] Anything not matching any of the above options. Set 'category' to 'unknownCategory'.
    
    <AVAILABLE_FUNCTIONS>
    {
            "name": "New-QFTicket",
            "description": "Generates Transaction Audits, Play Checks, Visual Round Results, Gameplay Statistics and Big Win Verification reports for the specified Player based on the provided parameters. If a parameter value cannot be identified in the request, do not specify any value for the parameter.",
            "properties": {
            "Login": {
                "type": "string",
                "description": "The players Login ID, Login Name or username. This is usually an alphanumeric string up to 20 characters long."
            },
            "CasinoId": {
                "type": "number",
                "description": "The numeric CasinoID or ServerID for the Casino that the player belongs to. This is a numeric value consisting of 4-5 digits. If a value for CasinoID cannot be found, do not specify this parameter and provide a CasinoName parameter instead."
            },
            "AuditEndDate": {
                "type": "string",
                "format": "date",
                "description": "The date of the most recent transactions to retrieve when generating Transaction audits in yyyy-mm-dd format. AuditEndDate must be after AuditStartDate. This is an optional parameter, if not specified this will be set to the current date. If this parameter is specified, the value should be one day after the intended date."
            },
            "TransactionIDs": {
                "type": "array",
                "description": "A list of game round Transaction ID numbers, or game round numbers, for which to generate Play Checks and visual round results. This is a 1-7 digit number, it may be included in a longer alphanumeric string seperated by hyphens, slashes or underscores. Multiple Transaction ID numbers may be provided in one request.",
                "items": {
                "type": "number"
                }
            },
            "AuditStartDate": {
                "type": "string",
                "format": "date",
                "description": "The date of the oldest transactions to retrieve when generating Transaction audits in yyyy-mm-dd format. AuditStartDate must be before AuditEndDate. This is an optional parameter, if not specified this will be set to 14 days before the current date. If this parameter is specified, the value should be one day prior to the intended date."
            },
            "CasinoName": {
                "type": "string",
                "description": "The name of the Casino site that the player belongs to. The matching CasinoID will be looked up. This is an optional parameter, as an alternative to the CasinoID parameter. If the string 'UAT' appears in this parameter, remove it."
            }
            },
            "required": [
            "Login",
            "TransactionIDs"
            ]
        }
    </AVAILABLE_FUNCTIONS>
    
    // Ex 1
    <CustomerInput>
    Your Reference: Whitehatgaming-#5109950
    Brand: Casimba.com
    Urgency: 3-Medium
    Affected Market: Colombia
    Is this a potential regulated market breach: Maybe
    Date of Occurence: 10/25/2023
    How Many Users Affected: One
    Related To?  : Casino Gameplay
    Casino Gameplay Related To: Gameplay Error
    Player ID / MGS Login Name : ollieb94
    Issue Description: Good Day,
    Please see the query below:
    Username: ollieb94
    User ID: 122556182
    Game Name / Provider: Unusual Suspects  - Northern Lights
    .Incident Date/ Time:25/10/2023 19:14:27
    .Bet ID/Comment:22923/3
    .Stake/Bet Value:13.79 GBP
    Details: The player received a bonus wheel and claims they have not received the bonus winnings of $50
        
    Kindly review for irregularities.
    Thank you
    </CustomerInput>
    Response:
    {
        "category": "winLegitimacy",
        "functions": [
            {
                "function_name": "New-QFTicket",
                "args": {
                    "Login": "ollieb94",
                    "CasinoId": null,
                    "AuditEndDate": "2023-10-26",
                    "TransactionIDs": [
                        22923
                    ],
                    "AuditStartDate": "2023-10-24",
                    "CasinoName": "Casimba.com"
                }
            }
        ]
    }
    
    // Ex 2
    <CustomerInput>
    Your Reference: Fluffy Favourites QA1 not Loading
    Brand: Unibet
    Urgency: 3-Medium
    Affected Market: Gibraltar
    Is this a potential regulated market breach: No
    Date of Occurence: 10/30/2023
    How Many Users Affected: One
    Related To?  : Casino Gameplay
    Casino Gameplay Related To: Game Launch Issue
        Player ID / MGS Login Name : N/A
    Issue Description: Hello GamesGlobal,
        
    When launching the game Fluffy Favourites , we are getting the attached error message.
        
    https://www-qa1.unibet.co.uk/play/fluffy-favourites#playforreal
        
    we have check with our development team and they confirm that game launch link is not working.
        
    https://etiloaderqf32.gameassists.co.uk/ETILoader/Error.aspx?productId=21599&languageCode=en
        
    please help to resolve this issue.
    </CustomerInput>
    Response:
    {
        "category": "gameLaunch",
        "functions": []
    }
    
    // Ex 3
    <CustomerInput>
    Your Reference: 111742217 // Big Win Verification 
    Brand: Bwin - Bwin.com 
    Urgency: 2-High 
    Affected Market: Italy 
    Is this a potential regulated market breach: Yes 
    Date of Occurence: 11/26/2023 
    How Many Users Affected: One 
    Related To?  : Casino Gameplay 
    Casino Gameplay Related To: Player Query 
     Player ID / MGS Login Name : 111742217 
    Casino ID / Server ID / Product ID : BWIN.IT 
    Issue Description: Hi Team,
    
    Please Verify the following win on Account ID: 111742217
    Please provide the winning images for these game rounds.
    
    Game Round Id:	111742217-41054
    Label:	BWIN.IT
    Game Name:	 Fishin' Bigger Pots of Gold
    Date:	11/26/2023 19:30:09 CET
    Bet:	7.50 EUR
    Win:	22,672.50 EUR
    
    Regards
    Srikanth Vaddi
    </CustomerInput>
    Response:
    {
        "category": "winLegitimacy",
        "functions": [
            {
                "function_name": "New-QFTicket",
                "args": {
                    "Login": "111742217",
                    "CasinoId": null,
                    "AuditEndDate": "2023-11-27",
                    "TransactionIDs": [
                        41054
                    ],
                    "AuditStartDate": "2023-11-25",
                    "CasinoName": "bwin.it"
                }
            }
        ]
    }
    // Real request
    <CustomerInput>
'@ + $Query + 
@'
    </CustomerInput>
    Reponse:
'@

    # build the JSON format request body, including the message content specified above.
    # functions section describes the New-QFTicket cmdlet to the AI so it can look for and generate parameters for this cmdlet

    $GPTInput = @{
        messages = @(
        @{
            role = 'user'
            content = $SystemMessage
        }
    )
    }| ConvertTo-JSON -Depth 6

    # Make the request to the OpenAI HTTP endpoint
    $Data = Invoke-RESTMethod -Method POST -Uri $GPTURI -ContentType 'application/json' -Headers @{ 'api-key' = $($GPTAPIKey|ConvertFrom-SecureString -AsPlainText) } -Body $GPTInput

    If ($null -ne $Data.Choices.message.content) {
        Write-Verbose ("Raw ChatGPT Response: " + $Data.Choices.message.content)
        # Convert response to a hashtable. The replace regex gets rid of '```json' markup that is sometimes inserted into the response
        $Response = $Data.Choices.message.content -replace '```(json)?',''|ConvertFrom-JSON -Depth 6 -AsHashtable
        # Process the function arguments provided in the reponse
        if ($Response.category -eq "winLegitimacy") {
            Write-Verbose "Win legitimacy / GPA ticket, processing function arguments..."
            # Add REQ Number if provided
            if ($REQNumber.trim() -ne '') {
                $Response.functions.args.Add('REQNumber',$REQNumber.trim())
            }
             # Append time of to 00.00.00 to AuditStartDate and 23:59:59 to AuditEndDate
            if ($null -ne $Response.functions.args.AuditStartDate) {
                $Response.functions.args.AuditStartDate = Get-Date $Response.functions.args.AuditStartDate -Format 'yyyy-MM-dd HH:mm:ss' -Hour 0 -Minute 0 -Second 0
            }
            if ($null -ne $Response.functions.args.AuditEndDate) {
                $Response.functions.args.AuditEndDate = Get-Date $Response.functions.args.AuditEndDate -Format 'yyyy-MM-dd HH:mm:ss' -Hour 23 -Minute 59 -Second 59
            }
            if ($null -eq $Response.functions.args.CasinoId -or $Response.functions.args.CasinoId -le 0 -or $Response.functions.args.CasinoId -eq "") {
                # Remove the CasinoID if it is null or 0 otherwise New-QFTicket will fail even if CasinoName is specified
                $Response.functions.args.remove('CasinoId')
            }
            if ($AutoMode -eq $True) {
                # Try calling the New-QFTicket function by splatting the parameters received from the AI!
                $TicketArgs = $Response.functions.args
                New-QFTicket @TicketArgs
            }
        }
        # Output an object containing the response to pipeline.
        $Response
    } else {
        Write-Host "No response received from ChatGPT."
    }
}